name: base
channels:
  - r
dependencies:
  - conda
  - open-fonts
  - openssl
  - pip
  - r-base=4.1.3
  - r-bsda
  - r-doparallel
  - r-expss
  - r-factominer
  - r-gam
  - r-glmnet
  - r-lme4
  - r-mice
  - r-splitstackshape
  - r-tictoc
  - r-xlsx
  - r-cyphr
  # - r-encryptr
  # - r-base=4.1.*
  # - r-daag - throws error
  # - r-eeptools - not in conda, ?unmaintained
  # - r-rdcomclient -?windows specific
  - pip:
    - jupyter-rsession-proxy
    - jupyter-server-proxy